### ISSUE TITLE
Expose API for custom resources of profiles and services

### ISSUE THREAD

**Issue by duynguyen** [adobe/aio-lib-campaign-standard#67]
For "custom resources" in ACS, there are currently 2 APIs being exposed:
* https://%tenantid%-adobeio.campaign.adobe.com/rest/customResources
* https://%tenantid%-adobeio.campaign.adobe.com/rest/profileAndServicesExt

In the SDK, we currently expose `getAllCustomResources()` method, which basically calls `/customResources` behind the scene. However we don't have any method for `/profileAndServicesExt`, which contains profile, services and linked customer resources.  

Therefore, we need to expose another method for `/profileAndServicesExt`, e.g. `getAllProfileCustomResources()`.

This will fix #60 .

**Comment by sandeep-paliwal** [comment]
Discussion related to #67 and #58 
We have campaign APIs, one which fetches normal resource data and other which gets custom/extended attributes (APIs with Ext in URL)
 
There are these two campaign sdk methods which behave opposite way

1.  `getAllCustomResources()` calls following API `/profileAndServicesExt/{CUSTOMRESOURCE}` and provides no way to call following API `/customResources/resourceType/{RESOURCE}`
2. `getMetadataForResource(resource)` calls `/profileAndServices/resourceType/{RESOURCE}` but no way to call `/profileAndServicesExt/resourceType/{RESOURCE}`

so we need to decide the how to make sdk calls consistent so by default they fetch normal data and then provide a way to get the custom/extended data.
There are two ways to fix this

1. Add a flag to current sdk calls. ex.
`getAllCustomResources(customResource, [parameters], fetchExt)` and `getMetadataForResource(resource, fetchExt)`
where `fetchExt` is boolean flag ( false by default)

2. Provide another sdk call explicitly for "Ext" data. ex/
 `getAllCustomResourcesExt(customResource, [parameters])` and `getMetadataForResourceExt(resource)`

Note in both proposed solutions we change the default behaviour of current `getAllCustomResources()` call.

@meryllblanchet @shazron @sarahxxu @duynguyen WDYT?

**Comment by shazron** [comment]
To avoid breaking current users, we should deprecate `getAllCustomResources` but keep the current behavior, and add two new functions (proposed names below)

`getAllCustomResources` -> existing function. same behavior (call `getAllProfileCustomResources` below). Add a deprecation notice in the JSDoc and logs. We will need to figure out how to surface this during a build so the user will see it.
`getAllBasicCustomResources` -> proposed name. new function, will use /customResources
`getAllProfileCustomResources` -> new function. will use /profileAndServicesExt

Similarly for `getMetaData...`

In the next major version, we remove the deprecated functions.

**Comment by duynguyen** [comment]
FYI - here is the feedback from the ACS API engineer when we asked about this issue:
> customResources: Contains only  customer resources but profileAndServicesExt contains profile, services and linked customer resources.
> Both API are different. I think it is better to expose two APIs.
> If you merge both a API, a developer may have issues with links (href) which may points  to the wrong API, Also the same resource can have two definition which is weird.
So I think option 2 is better as well.
For `/profileAndServicesExt`, I feel that `getAllProfileCustomResources` doesn't cover enough (no "services"). How about `getAllProfileAndServicesExt` ?

**Comment by sarahxxu** [comment]
+1 how about the following for naming

- `getAllCustomResources` -> existing function. same behavior (call getAllProfileCustomResources below). Add a deprecation notice in the JSDoc and logs. We will need to figure out how to surface this during a build so the user will see it.
- `getAllCustomResources` -> proposed name. new function, will use /customResources
- `getAllProfileAndServicesExt` -> new function. will use /profileAndServicesExt

**Comment by shazron** [comment]
@sarahxxu I think the first and second bullet points in your comment have the same name?

**Comment by sarahxxu** [comment]
Thanks for catching it!
I realized that we have an existing `getCustomResources`, which in my opinion would be the best name for the new function, to call /customResources. Does the current `getCustomResources` really points to `getProfileCustomResources`?
cc @shazron

**Comment by shazron** [comment]
@sarahxxu I think there is misunderstanding.

This proposal has nothing to do with `getCustomResources`, but `getAllCustomResources` which returns different data. It's hard to explain the differences without access to the original API page, which has been converted to a new docs page that doesn't have the same examples. Thus, we need a new name.
