### ISSUE TITLE
getMetadataForResourceExt returns data instead of metadata

### ISSUE THREAD

**Issue by JaapTrum** [adobe/aio-lib-campaign-standard#84]
The function campaignStandardCoreAPI.getMetadataForResourceExt("profile") is returning profile-data rather than profile-metadata. from reading the docs I'd assume that this would return the metadata including custom objects (fields, filters, etc).

Is this correct behavior?

I'm on 2.1.3 (latest)

**Comment by meryllblanchet** [comment]
Hi @JaapTrum thanks for raising the issue.

Let's ask @shazron @sandeep-paliwal 's feedback

**Comment by sandeep-paliwal** [comment]
@JaapTrum I see that the campaign API being called for `getMetadataForResourceExt` is `https://mc.adobe.io/<tenantId>/campaign/profileAndServicesExt/profile`
Can you confirm that thats the underlying API you expect to be called when calling `getMetadataForResourceExt` ?

**Comment by JaapTrum** [comment]
@sandeep-paliwal 
That's what I thought is being called, it returns profiles (data).

However, the function is called getMetadataForResourceExt(resource) (and has the description "Get the Ext metadata information for a resource."), which would make me assume that it should return metadata and the "Ext" (probably) means something like "Extensions". Leading me to expect the API to be called to be this one:

https://mc.adobe.io/<tenantId>/campaign/profileAndServicesExt/resourceType/<parameter "resource">
(Where the parameter "resource" can be any table)

This API returns the metadata for the resource (including custom objects/extensions).



If this is the case, you might need to check the getMetadataForResource(resource) function too. As this should then be calling the API:
https://mc.adobe.io/<tenantId>/campaign/profileAndServices/resourceType/<parameter "resource">
(Where the parameter "resource" can be 'profile', 'service' or 'history')

**Comment by sandeep-paliwal** [comment]
I guess we need to update function documentation to make things more clear. The API description [here](https://experienceleague.adobe.com/docs/campaign-standard/using/working-with-apis/global-concepts/custom-resources.html?lang=en#working-with-apis) suggests that it returns custom resources for the given resourceType
